# version: '3.8'
services:
  # frontend:
  #   container_name: nft-frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - '80:80'
  #   environment:
  #     - REACT_APP_API_URL=http://backend:3000
  #   depends_on:
  #     - backend
  #   networks:
  #     - nft-network

  backend:
    container_name: nft-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      # - blockchain
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - nft-network

  mongo:
    image: mongo:latest
    container_name: nft-mongo
    command: mongod --replSet rs0 --bind_ip_all
    # ports:
    #   - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - nft-network

  blockchain:
    container_name: nft-blockchain
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - '8545:8545'
    # environment:
    #   - PRIVATE_KEY=${PRIVATE_KEY}
    volumes:
      - ./blockchain:/app
    restart: always
    networks:
      - nft-network

volumes:
  mongo-data:
    driver: local

networks:
  nft-network:
    driver: bridge
