version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - REACT_APP_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - nft-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nft_marketplace
      - BLOCKCHAIN_URL=http://blockchain:8545
      - PRIVATE_KEY=${PRIVATE_KEY}
      - BALANCE_MANAGER_ADDRESS=${BALANCE_MANAGER_ADDRESS}
      - NFT_MARKET_ADDRESS=${NFT_MARKET_ADDRESS}
    depends_on:
      - mongo
      - blockchain
    networks:
      - nft-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - nft-network

  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - '8545:8545'
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
    volumes:
      - ./blockchain:/app
    networks:
      - nft-network

volumes:
  mongo-data:

networks:
  nft-network:
    driver: bridge
